<?php

namespace Database\Seeders;

use App\Models\Huruf;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;
use Illuminate\Support\Facades\DB;

class HurufSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();

        DB::table('hurufs')->insert([
            // Hiragana - Gojuon
            [
                'id' => 'H-GO-A',
                'huruf' => 'あ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal pertama dalam hiragana.',
                'romaji' => 'a',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => 'https://res.cloudinary.com/dzozxilf6/video/upload/v1747231147/53_y9ya3g.wav',
                'catatan' => null,
               
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-I',
                'huruf' => 'い',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal kedua dalam hiragana.',
                'romaji' => 'i',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-U',
                'huruf' => 'う',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal ketiga dalam hiragana.',
                'romaji' => 'u',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-E',
                'huruf' => 'え',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal keempat dalam hiragana.',
                'romaji' => 'e',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-O',
                'huruf' => 'お',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal kelima dalam hiragana.',
                'romaji' => 'o',
                'jumlah_coretan' => 3,
                'kategori' => 'vokal',
                'groups' => 'a',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KA',
                'huruf' => 'か',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "k" pertama dalam hiragana.',
                'romaji' => 'ka',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KI',
                'huruf' => 'き',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "k" kedua dalam hiragana.',
                'romaji' => 'ki',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KU',
                'huruf' => 'く',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "k" ketiga dalam hiragana.',
                'romaji' => 'ku',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KE',
                'huruf' => 'け',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "k" keempat dalam hiragana.',
                'romaji' => 'ke',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-KO',
                'huruf' => 'こ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "k" kelima dalam hiragana.',
                'romaji' => 'ko',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'ka',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SA',
                'huruf' => 'さ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" pertama dalam hiragana.',
                'romaji' => 'sa',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SHI',
                'huruf' => 'し',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" kedua dalam hiragana. Dibaca "shi", bukan "si".',
                'romaji' => 'shi',
                'jumlah_coretan' => 1,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SU',
                'huruf' => 'す',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" ketiga dalam hiragana.',
                'romaji' => 'su',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SE',
                'huruf' => 'せ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" keempat dalam hiragana.',
                'romaji' => 'se',
                'jumlah_coretan' => 3,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-GO-SO',
                'huruf' => 'そ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "s" kelima dalam hiragana.',
                'romaji' => 'so',
                'jumlah_coretan' => 2,
                'kategori' => 'konsonan',
                'groups' => 'sa',
                'audio' => null,
                'catatan' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
         
            // Hiragana - Dakuten
            [
                'id' => 'H-DA-GA',
                'huruf' => 'が',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Bersuara dari "ka", digunakan dalam kata benda.',
                'romaji' => 'ga',
                'jumlah_coretan' => 3,
                'kategori' => 'non vokal',
                'groups' => 'ga',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-GI',
                'huruf' => 'ぎ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Bersuara dari "ki".',
                'romaji' => 'gi',
                'jumlah_coretan' => 3,
                'kategori' => 'non vokal',
                'groups' => 'ga',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'H-DA-GU',
                'huruf' => 'ぐ',
                'jenis_huruf' => 'hiragana',
                'kategori_huruf' => 'dakuten',
                'deskripsi' => 'Bersuara dari "ku".',
                'romaji' => 'gu',
                'jumlah_coretan' => 3,
                'kategori' => 'non vokal',
                'groups' => 'ga',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Katakana - Gojuon
            [
                'id' => 'K-GO-A',
                'huruf' => 'ア',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf vokal pertama dalam katakana.',
                'romaji' => 'a',
                'jumlah_coretan' => 2,
                'kategori' => 'vokal',
                'groups' => 'a',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-KA',
                'huruf' => 'カ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "ka" dalam katakana.',
                'romaji' => 'ka',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'ka',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-GO-SA',
                'huruf' => 'サ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'gojuon',
                'deskripsi' => 'Huruf konsonan "sa" dalam katakana.',
                'romaji' => 'sa',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'sa',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Katakana - Handakuten
            [
                'id' => 'K-HA-PA',
                'huruf' => 'パ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Bersuara dari "ha" menggunakan simbol lingkaran kecil.',
                'romaji' => 'pa',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'pa',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-HA-PI',
                'huruf' => 'ピ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Bersuara dari "hi" menggunakan simbol lingkaran kecil.',
                'romaji' => 'pi',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'pa',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'id' => 'K-HA-PU',
                'huruf' => 'プ',
                'jenis_huruf' => 'katakana',
                'kategori_huruf' => 'handakuten',
                'deskripsi' => 'Bersuara dari "fu" (hu) menggunakan simbol lingkaran kecil.',
                'romaji' => 'pu',
                'jumlah_coretan' => 2,
                'kategori' => 'non vokal',
                'groups' => 'pa',
                'catatan' => null,
                'audio' => null,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ]);
    }
}
